networks:
  b0:
    driver: bridge

services:
  node:
    image: creatorsim/creator-checker
    pull_policy: missing # Revisa si existe localmente; si no está, hace pull
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: bind
        source: /lib/modules
        target: /lib/modules
    networks:
      - b0
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    privileged: true
    cap_add:
      - ALL
    ports:
      - "8000:8000"
